import Vue from 'vue';
import HelloWorld from '@/components/HelloWorld.vue';
import Navbar from '@/components/Navbar.vue';
import Parallax from '@/components/Parallax.vue';
import NavigationDrawer from '@/components/NavigationDrawer.vue';
import Calendar from '@/components/Calendar.vue';
import DialogTimePicker from '@/components/DialogTimePicker.vue';
import TimePicker from '@/components/TimePicker.vue';
import ConfirmDel from '@/components/ConfirmDel.vue';
import DialogNewStore from '@/components/DialogNewStore.vue';

Vue.component('HelloWorld', HelloWorld);
Vue.component('Navbar', Navbar);
Vue.component('Parallax', Parallax);
Vue.component('NavigationDrawer', NavigationDrawer);
Vue.component('Calendar', Calendar);
Vue.component('DialogTimePicker', DialogTimePicker);
Vue.component('TimePicker', TimePicker);
Vue.component('ConfirmDel', ConfirmDel);
Vue.component('DialogNewStore', DialogNewStore);
